<?php
include('GetNewToken.php');


function Get_List_Device($token){
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api.spotify.com/v1/me/player/devices');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Content-Type: application/json';
$headers[] = 'Authorization: Bearer '.$token;
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
$jsonObj = json_decode($result);

$tab = array(array());
for ( $i = 0 ; $i<count($jsonObj->devices) ; $i++ ){
        $tab[$i][0] = $jsonObj->devices[$i]->id;   // Device ID
        $tab[$i][1] = $jsonObj->devices[$i]->name;   // Device name
        $tab[$i][2] = $jsonObj->devices[$i]->type;   // Device type
        $tab[$i][3] = $jsonObj->devices[$i]->volume_percent;   // Device volume
        $tab[$i][4] = 0;
}
    return array($tab,count($jsonObj->devices));

}


function Test_Device($token){
    $list = Get_List_Device($token);
    if ( $list[1]==0){
      echo "\n\033[33m |---------------------------| \033[0m\n";
        echo "\033[33m | Pas d'appareils connectés |\033[0m\n";
        echo "\033[33m |---------------------------| \033[0m\n\n";
        return array(false,$list);
    }
    else {
      echo "\n\033[32m |-----------------------------| \033[0m\n";
        echo "\033[32m | ".$list[1]." appareil(s) connecté(s) : |\033[0m\n";
        echo "\033[32m |-----------------------------| \033[0m\n\n";
        print_r($list[0][0]);
        return array(true,$list);
    }

}

function Choose_Device($token,$num){
    $test = Test_Device($token);
    $list = $test[1];
        if( $test[0] == true){
            echo "\nDevice choisi ID : " . $list[$num][0][0];
            echo "\nDevice choisi name : " . $list[$num][0][1]."\n";
        return $list[$num][0][0];
        } else {
        return -1;
    }
    }
$device_id = Choose_Device($token, 0);


echo $token . "\n";


