<?php
include('GetNewToken.php');


// Renvoie tab avec la recherche en prenant un token et string 
function SearchTrack($token,$name_search,$limit=10)
{
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, 'https://api.spotify.com/v1/search?q='.$name_search.'&type=track&market=FR&limit='.$limit);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


    $headers = array();
    $headers[] = 'Accept: application/json';
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Authorization: Bearer ' . $token;
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
    $jsonObj2 = json_decode($result);

    $tab = array(array());
    for($i=0;$i<$limit;$i++){
        $tab[$i][0] = $jsonObj2->tracks->items[$i]->name ;  // Name
        $tab[$i][1] = $jsonObj2->tracks->items[$i]->album->artists[0]->id; //Song ID
        $tab[$i][2] = $jsonObj2->tracks->items[$i]->preview_url; // Song preview
        $tab[$i][3] = $jsonObj2->tracks->items[$i]->popularity; // Song popularity
        $tab[$i][4] = $jsonObj2->tracks->items[$i]->album->images[0]->url; // Song url
        $tab[$i][5] = $jsonObj2->tracks->items[$i]->album->release_date; // Song date
        $tab[$i][6] = $jsonObj2->tracks->items[$i]->album->artists[0]->name; // Artiste Nam
        $tab[$i][7] = $jsonObj2->tracks->items[$i]->album->artists[0]->id; // Artiste ID
        $tab[$i][8] = $jsonObj2->tracks->items[$i]->uri ;  // URI
        $tab[$i][9] = $jsonObj2->tracks->items[$i]->album->images[0]->url; // Song url$i][10] = $jsonObj2->tracks->items[$i]->ablum->name; //Album Name
        $tab[$i][10] = $jsonObj2->tracks->items[$i]->ablum->name; //Album Name
        $tab[$i][11] = 0;  // If add song 
        }



     
 // echo $result;
    return $tab;
}
function Test_SearchTrack($token) // OK
{
    $fill = "Test";

    $tab = SearchTrack($token, str_replace(' ', '%20', $fill), 5);

    print_r($tab);
}

//Test_SearchTrack($token);


